{% set name = "sacc" %}
{% set version = "2.3" %}

package:
  name: {{ name|lower }}
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 70aff1b0c73bb3eb98e55e64d5917b267416e8e2651ab2e863049b6ff3eac529

build:
  noarch: python
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm <7
    - setuptools_scm_git_archive
  run:
    - python >={{ python_min }}
    - astropy-base
    - scipy
    - numpy

test:
  requires:
    - python {{ python_min }}
  imports:
    - sacc

about:
  home: https://github.com/LSSTDESC/sacc
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Save All Correlations and Covariances

extra:
  recipe-maintainers:
    - joezuntz
    - beckermr
